CATEGORY_NAME_MAX_LENGTH = 128
TAG_CATEGORY_FIELD_MAX_LENGTH = 128
PRODUCT_NAME_FIELD_MAX_LENGTH = 256
PRODUCT_SLUG_FIELD_MAX_LENGTH = 128
MIN_VALUE_VALIDATOR_PRICE = 1
MAX_VALUE_VALIDATOR_PRICE = 20000000
MIN_VALUE_VALIDATOR_AMOUNT = 1
MAX_VALUE_VALIDATOR_AMOUNT = 32000
