# Generated by Django 4.2.16 on 2024-09-13 14:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории, не более             128 символов', max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Слаг категории, не более             128 символов', max_length=128, unique=True, verbose_name='Слаг')),
                ('picture', models.ImageField(help_text='Изображение категории', upload_to='backend/categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта, не более             256 символов', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Слаг продукта, не более             128 символов', max_length=128, unique=True, verbose_name='Слаг')),
                ('price', models.PositiveIntegerField(help_text='Цена продукта', validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше,                     чем 1'), django.core.validators.MaxValueValidator(20000000, message='Значение не может быть больше,                     чем 20000000')], verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название подкатегории, не более             128 символов', max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Слаг подкатегории, не более             128 символов', max_length=128, unique=True, verbose_name='Слаг')),
                ('picture', models.ImageField(help_text='Изображение подкатегории', upload_to='backend/categories/', verbose_name='Изображение')),
                ('category', models.ForeignKey(help_text='К какой категории относится данная подкатегория', on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, help_text='Количество продуктов', validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше,                     чем 1'), django.core.validators.MaxValueValidator(32000, message='Значение не может быть больше,                     чем 1')], verbose_name='Количество')),
                ('product', models.ForeignKey(help_text='Продукт, добавленный пользователем.', on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(help_text='Пользователь, который добавил продукт.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(help_text='К какой подкатегории относится продукт', on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='Подкатегория продукта'),
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение продукта', upload_to='backend/products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'изображения продукта',
            },
        ),
    ]
