# Generated by Django 4.2.16 on 2024-09-11 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_imageproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество продуктов', validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше,                     чем 1'), django.core.validators.MaxValueValidator(32000, message='Значение не может быть больше,                     чем 1')], verbose_name='Количество'),
        ),
    ]
