# Generated by Django 4.2.16 on 2024-09-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shoppingcart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество продуктов', verbose_name='Количество'),
        ),
    ]
